-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  title text,
  price numeric,
  description text,
  category text,
  image text,
  rating numeric
);

-- Create Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  user_email text,
  amount numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  items jsonb
);
